{
 "title": "AARC Field Day 2016",
 "time": { "from": "2016-06-25T18:00:00.000Z", "to": "2016-06-26T17:59:59.000Z" },
 "panels": [
  {
   "title": "Contacts per Hour",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mode_rate",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "AARC Contacts",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 13, "x": 5, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "geohash" ], "type": "tag" }
     ],
     "measurement": "qso_location",
     "rawSql": "SELECT\n  count(state) as metric\nFROM table aarc_fd\nWHERE $__timeFilter(time_sec)\nORDER BY time_sec ASC\n"
    }
   ]
  },
  {
   "title": "Lastest Contacts",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "measurement": "qso_location", "rawSql": "SELECT 1" }
   ]
  },
  {
   "title": "Top Operators (Max Contacts per Hour)",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Operator" ], "type": "tag" }
     ],
     "measurement": "op_rate",
     "rawSql": "SELECT 1"
    }
   ]
  },
  {
   "title": "Band Activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Band" ], "type": "tag" }
     ],
     "measurement": "qso_location",
     "rawSql": "SELECT 1"
    }
   ]
  },
  {
   "title": "Mode Activity",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Mode" ], "type": "tag" }
     ],
     "measurement": "qso_points",
     "select": [
      [
       { "params": [ "Contacts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Contacts" ], "type": "alias" }
      ],
      [
       { "params": [ "Points" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Points" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Station Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Station" ], "type": "tag" }
     ],
     "measurement": "station_info",
     "rawSql": "SELECT 1",
     "tags": [
      { "key": "Station", "operator": "=", "value": "STATION1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "Station" ], "type": "tag" }
     ],
     "measurement": "station_info",
     "select": [
      [
       { "params": [ "Operator" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Operator" ], "type": "alias" }
      ],
      [
       { "params": [ "Mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Mode" ], "type": "alias" }
      ],
      [
       { "params": [ "Band" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Band" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Station", "operator": "=", "value": "STATION2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "Station" ], "type": "tag" }
     ],
     "measurement": "station_info",
     "select": [
      [
       { "params": [ "Operator" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Operator" ], "type": "alias" }
      ],
      [
       { "params": [ "Mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Mode" ], "type": "alias" }
      ],
      [
       { "params": [ "Band" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Band" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Station", "operator": "=", "value": "STATION3" }
     ]
    }
   ]
  },
  { "title": "UTC", "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 } },
  {
   "title": "Contact Rate (Contacts per Hour)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mode_rate",
     "rawSql": "SELECT\n  count(operator),\n  'count' as metric\nFROM aarc_fd\nWHERE operator \nGROUP BY time\nORDER BY time\n"
    }
   ]
  }
 ]
}